import type { Talisman, Grade } from '../types';

export const GRADE_COLORS: Record<Grade, { bg: string; text: string; sub: string }> = {
  legend: { bg: '#fff8e1', text: '#ff9100', sub: '#ffecb3' },
  rare:   { bg: '#f4edff', text: '#a25df5', sub: '#e8d9ff' },
  common: { bg: '#ffffff', text: '#191f28', sub: '#f2f4f6' },
};

export const INITIAL_TALISMAN_DATA: Talisman[] = [
  // common (id 1~31)
  { id: 1,  unlocked: false, name: '윙크 명태',       grade: 'common', img: '/uploads/common/common_amulet_01.png' },
  { id: 2,  unlocked: false, name: '깜짝 명태',       grade: 'common', img: '/uploads/common/common_amulet_02.png' },
  { id: 3,  unlocked: false, name: '겁먹은 명태',     grade: 'common', img: '/uploads/common/common_amulet_03.png' },
  { id: 4,  unlocked: false, name: '화난 명태',       grade: 'common', img: '/uploads/common/common_amulet_04.png' },
  { id: 5,  unlocked: false, name: '반짝이는 명태',   grade: 'common', img: '/uploads/common/common_amulet_05.png' },
  { id: 6,  unlocked: false, name: '슬픈 명태',       grade: 'common', img: '/uploads/common/common_amulet_06.png' },
  { id: 7,  unlocked: false, name: '메롱 명태',       grade: 'common', img: '/uploads/common/common_amulet_07.png' },
  { id: 8,  unlocked: false, name: '기본 명태',       grade: 'common', img: '/uploads/common/common_amulet_08.png' },
  { id: 9,  unlocked: false, name: '잠자는 명태',     grade: 'common', img: '/uploads/common/common_amulet_09.png' },
  { id: 10, unlocked: false, name: '사악한 명태',     grade: 'common', img: '/uploads/common/common_amulet_10.png' },
  { id: 11, unlocked: false, name: '짝사랑 명태',     grade: 'common', img: '/uploads/common/common_amulet_11.png' },
  { id: 12, unlocked: false, name: '뽀뽀 명태',       grade: 'common', img: '/uploads/common/common_amulet_12.png' },
  { id: 13, unlocked: false, name: '승리자 명태',     grade: 'common', img: '/uploads/common/common_amulet_13.png' },
  { id: 14, unlocked: false, name: '초롱초롱 명태',   grade: 'common', img: '/uploads/common/common_amulet_14.png' },
  { id: 15, unlocked: false, name: '익살 명태',       grade: 'common', img: '/uploads/common/common_amulet_15.png' },
  { id: 16, unlocked: false, name: '노곤 명태',       grade: 'common', img: '/uploads/common/common_amulet_16.png' },
  { id: 17, unlocked: false, name: '배부른 명태',     grade: 'common', img: '/uploads/common/common_amulet_17.png' },
  { id: 18, unlocked: false, name: '감탄 명태',       grade: 'common', img: '/uploads/common/common_amulet_18.png' },
  { id: 19, unlocked: false, name: '반장대소 명태',   grade: 'common', img: '/uploads/common/common_amulet_19.png' },
  { id: 20, unlocked: false, name: '식은땀 명태',     grade: 'common', img: '/uploads/common/common_amulet_20.png' },
  { id: 21, unlocked: false, name: '명상 명태',       grade: 'common', img: '/uploads/common/common_amulet_21.png' },
  { id: 22, unlocked: false, name: '부끄 명태',       grade: 'common', img: '/uploads/common/common_amulet_22.png' },
  { id: 23, unlocked: false, name: '열정 명태',       grade: 'common', img: '/uploads/common/common_amulet_23.png' },
  { id: 24, unlocked: false, name: '비웃는 명태',     grade: 'common', img: '/uploads/common/common_amulet_24.png' },
  { id: 25, unlocked: false, name: '의욕제로 명태',   grade: 'common', img: '/uploads/common/common_amulet_25.png' },
  { id: 26, unlocked: false, name: '흥얼 명태',       grade: 'common', img: '/uploads/common/common_amulet_26.png' },
  { id: 27, unlocked: false, name: '도파민 명태',     grade: 'common', img: '/uploads/common/common_amulet_27.png' },
  { id: 28, unlocked: false, name: '의심 명태',       grade: 'common', img: '/uploads/common/common_amulet_28.png' },
  { id: 29, unlocked: false, name: '발랄 명태',       grade: 'common', img: '/uploads/common/common_amulet_29.png' },
  { id: 30, unlocked: false, name: '밤샌 명태',       grade: 'common', img: '/uploads/common/common_amulet_30.png' },
  { id: 31, unlocked: false, name: '피곤 명태',       grade: 'common', img: '/uploads/common/common_amulet_31.png' },
  // rare (id 32~68)
  { id: 32, unlocked: false, name: '천문학자 명태',       grade: 'rare', img: '/uploads/rare/rare_amulet_01.png' },
  { id: 33, unlocked: false, name: '패션디자이너 명태',   grade: 'rare', img: '/uploads/rare/rare_amulet_02.png' },
  { id: 34, unlocked: false, name: '건축가 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_03.png' },
  { id: 35, unlocked: false, name: '보석감정사 명태',     grade: 'rare', img: '/uploads/rare/rare_amulet_04.png' },
  { id: 36, unlocked: false, name: '엔지니어 명태',       grade: 'rare', img: '/uploads/rare/rare_amulet_05.png' },
  { id: 37, unlocked: false, name: '해양학자 명태',       grade: 'rare', img: '/uploads/rare/rare_amulet_06.png' },
  { id: 38, unlocked: false, name: '기상학자 명태',       grade: 'rare', img: '/uploads/rare/rare_amulet_07.png' },
  { id: 39, unlocked: false, name: '고고학자 명태',       grade: 'rare', img: '/uploads/rare/rare_amulet_08.png' },
  { id: 40, unlocked: false, name: '플로리스트 명태',     grade: 'rare', img: '/uploads/rare/rare_amulet_09.png' },
  { id: 41, unlocked: false, name: '스쿠버다이버 명태',   grade: 'rare', img: '/uploads/rare/rare_amulet_10.png' },
  { id: 42, unlocked: false, name: '연주가 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_11.png' },
  { id: 43, unlocked: false, name: '공원관리자 명태',     grade: 'rare', img: '/uploads/rare/rare_amulet_12.png' },
  { id: 44, unlocked: false, name: '정비사 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_13.png' },
  { id: 45, unlocked: false, name: '파티시에 명태',       grade: 'rare', img: '/uploads/rare/rare_amulet_14.png' },
  { id: 46, unlocked: false, name: '안전관리자 명태',     grade: 'rare', img: '/uploads/rare/rare_amulet_15.png' },
  { id: 47, unlocked: false, name: '우주비행사 명태',     grade: 'rare', img: '/uploads/rare/rare_amulet_16.png' },
  { id: 48, unlocked: false, name: '교사 명태',           grade: 'rare', img: '/uploads/rare/rare_amulet_17.png' },
  { id: 49, unlocked: false, name: '재즈음악가 명태',     grade: 'rare', img: '/uploads/rare/rare_amulet_18.png' },
  { id: 50, unlocked: false, name: '영화감독 명태',       grade: 'rare', img: '/uploads/rare/rare_amulet_19.png' },
  { id: 51, unlocked: false, name: '수의사 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_20.png' },
  { id: 52, unlocked: false, name: '승무원 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_21.png' },
  { id: 53, unlocked: false, name: '집배원 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_22.png' },
  { id: 54, unlocked: false, name: '정원사 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_23.png' },
  { id: 55, unlocked: false, name: '해커 명태',           grade: 'rare', img: '/uploads/rare/rare_amulet_24.png' },
  { id: 56, unlocked: false, name: '의사 명태',           grade: 'rare', img: '/uploads/rare/rare_amulet_25.png' },
  { id: 57, unlocked: false, name: '소방관 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_26.png' },
  { id: 58, unlocked: false, name: '경찰관 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_27.png' },
  { id: 59, unlocked: false, name: '판사 명태',           grade: 'rare', img: '/uploads/rare/rare_amulet_28.png' },
  { id: 60, unlocked: false, name: '설계사 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_29.png' },
  { id: 61, unlocked: false, name: '헤어디자이너 명태',   grade: 'rare', img: '/uploads/rare/rare_amulet_30.png' },
  { id: 62, unlocked: false, name: '메이크업아티스트 명태', grade: 'rare', img: '/uploads/rare/rare_amulet_31.png' },
  { id: 63, unlocked: false, name: '네일아티스트 명태',   grade: 'rare', img: '/uploads/rare/rare_amulet_32.png' },
  { id: 64, unlocked: false, name: '회계사 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_33.png' },
  { id: 65, unlocked: false, name: '조향사 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_34.png' },
  { id: 66, unlocked: false, name: '재판사 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_35.png' },
  { id: 67, unlocked: false, name: '개발자 명태',         grade: 'rare', img: '/uploads/rare/rare_amulet_36.png' },
  { id: 68, unlocked: false, name: '사서 명태',           grade: 'rare', img: '/uploads/rare/rare_amulet_37.png' },
  // legend (id 69~84)
  { id: 69, unlocked: false, name: '태양 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_01.png' },
  { id: 70, unlocked: false, name: '무지개 명태', grade: 'legend', img: '/uploads/legend/legend_amulet_02.png' },
  { id: 71, unlocked: false, name: '황금 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_03.png' },
  { id: 72, unlocked: false, name: '구름 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_04.png' },
  { id: 73, unlocked: false, name: '번개 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_05.png' },
  { id: 74, unlocked: false, name: '수호신 명태', grade: 'legend', img: '/uploads/legend/legend_amulet_06.png' },
  { id: 75, unlocked: false, name: '얼음 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_07.png' },
  { id: 76, unlocked: false, name: '불꽃 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_08.png' },
  { id: 77, unlocked: false, name: '밤 명태',     grade: 'legend', img: '/uploads/legend/legend_amulet_09.png' },
  { id: 78, unlocked: false, name: '보석 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_10.png' },
  { id: 79, unlocked: false, name: '사탕 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_11.png' },
  { id: 80, unlocked: false, name: '모래 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_12.png' },
  { id: 81, unlocked: false, name: '바람 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_13.png' },
  { id: 82, unlocked: false, name: '어둠 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_14.png' },
  { id: 83, unlocked: false, name: '화산 명태',   grade: 'legend', img: '/uploads/legend/legend_amulet_15.png' },
  { id: 84, unlocked: false, name: '숲 명태',     grade: 'legend', img: '/uploads/legend/legend_amulet_16.png' },
];

export const HIDDEN_TALISMAN_DATA: Talisman[] = [];

export const STORAGE_KEYS = {
  TALISMAN_DATA: 'talisman_data',
  CREDITS: 'talisman_credits',
  WISH: 'talisman_wish',
};